# -*- coding: utf-8 -*-
"""sequenciaFibonacci

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oeVm8yAZ8E0IgL8imdca3p6c5bAoFaPH
"""

#INÍCIO CABEÇALHO 
print('-'*30)
print('SEQUENCIA DE FIBONACCI')
print('-'*30)
#FIM CABEÇALHO 

#INÍCIO DO CÓDIGO - Entrada de dados
num = int(input('Quantos termos da sequência de Fibonacci você desejar mostrar: ')) #aqui o usuário ira entrar com os dados
t1 = 0 #1º termo da minha lista 
t2 = 1 #2º termo da minha lista
cont = 3 #esta iniciando no termo 3 por o termo 1 e 2 ja foram dados 

#GUARDANDO VALORES NA LISTA
lista = [t1, t2] #a lista inicia com o 1º e 2º termo

#LOOP
while cont <= num: #enquanto o contador for menor ou igual a quantidade de termos que o usuário digitar o programa executará o código abaixo. 
    t3 = t1 + t2 #Definição da sequencia de Fibonacci ('o próximo termo da sequencia é sempre a soma do ultimo com o penultimo termo')
    lista.append(t3) #adicionando o resultado da soma acima na lista. Após adicionar esse valor na lista, ele continua a leitura da linha debaixo
    t1 = t2 #agora o último termo sera o 1º para ser aplicado na formula do t3
    t2 = t3 #o t2 presente na fórmula do t3, sera = o t3 resultante do cálculo anterior
    cont = cont + 1 #contador. Toda vez que ele fizer 1 loop, sera aqui contabilizado (lembrando que o contador inicia em 3 pois o 1º e 2º termo nós ja temos)
print() #código para pular linha - separar o código
print('A sequência de Fibonacci é: ', lista)